const download_links = {
    "mega": "mega.nz",
    "yandex": "yadi.sk",
    "mail": "mail.ru",
    "users": "userscloud.com",
    "pcloud": "my.pcloud.com",
    "onedrive": "1drv.ms",
    "onedrive": "onedrive.live",
    "gdrive": "drive.google.com",
    "mediafire": "mediafire.com",
    "ddl.to": "ddl.to",
    "openload": "oload.life",
    "download.ru": "download.ru"
}

const watch_links = {
    "vk": "vk.com",
    "tune": "tune.pk",
    "sendvid": "sendvid.com",
    "openload": "oload.life",
    "sibnet": "video.sibnet.ru",
    "gdrive": "drive.google.com",
    "ok.ru": "ok.ru",
    "dailymotion": "dailymotion.com",
    "mail.ru": "my.mail.ru",
    "mega": "mega.nz",
    "myvi": "myvi.ru",
    "mp4upload": "mp4upload.com",
    "cloudvideo": "cloudvideo.tv",
    "hdvid": "hdvid.tv",
    "rapidvideo": "rapidvideo.com",
    "rapidvideo": "rapidvid.to",
    "streamango": "streamango.com",
    "userscloud": "userscloud.com",
    "yourupload": "yourupload.com",
    "fembed": "www.fembed.com",
    "youtube": "youtu.be",
    "youtube": "youtube.com",
    "rutube": "rutube.ru",
    "vidfast": "vidfast.co",
    "vidia": "vidia.tv",
    "vidsat": "vidsat.net",
    "supervideo": "supervideo.tv",
    "clipwatching": "clipwatching.com",
    "jetload": "jetload.net",
    "fastplay": "fastplay.to",
    "mystream": "mystream.to",
    "streamwire": "streamwire.net"
}

module.exports = { download_links, watch_links }