module.exports = {
    "+18": "+18",
    "Action": "Aksiyon",
    "Adventure": "Macera",
    "Cars": "Arabalar",
    "Comedy": "Komedi",
    "Dementia": "Kişilik Bölünmesi",
    "Demons": "Şeytanlar",
    "Drama": "Dram",
    "Ecchi": "Ecchi",
    "Fantasy": "Fantastik",
    "Game": "Oyun",
    "Harem": "Harem",
    "Hentai": "Hentai",
    "Historical": "Tarihi",
    "Horror": "Korku",
    "Josei": "Josei",
    "Kids": "Çocuklar",
    "Magic": "Büyü",
    "Martial Arts": "Dövüş Sanatları",
    "Mecha": "Mecha",
    "Military": "Askeri",
    "Music": "Müzik",
    "Mystery": "Gizem",
    "Parody": "Parodi",
    "Police": "Polis",
    "Psychological": "Psikolojik",
    "Romance": "Romantizm",
    "Samurai": "Samuray",
    "School": "Okul",
    "Sci-Fi": "Bilim Kurgu",
    "Seinen": "Seinen",
    "Shoujo": "Shoujo",
    "Shoujo Ai": "Shoujo Ai",
    "Shounen": "Shounen",
    "Shounen Ai": "Shounen Ai",
    "Slice of Life": "Günlük Yaşam",
    "Space": "Uzay",
    "Sports": "Sporlar",
    "Super Power": "Süper Güçler",
    "Supernatural": "Doğaüstü",
    "Thriller": "Gerilim",
    "Vampire": "Vampir",
    "Yaoi": "Yaoi",
    "Yuri": "Yuri"
}